### ISSUE TITLE
Unexpected: any yaml file treated as migration

### ISSUE THREAD

**Issue by tkivisik** [emicklei/gmig#26]
Currently, all yaml files are treated (found) as migration files.

`gmig status project` will list all yaml files, even when they don't follow the naming convention (currently starts with a timestamp, future starts with an index)

I propose that a check be made to verify whether a yaml file follows a migration file naming convention.

**Comment by emicklei** [comment]
well, that's it unavoidable. The format is not really fixed ; the user is responsbile for choosing a name strategy such that the order is preserved. `gmig` works with yaml files, that is a given. I think therefore it is expected the each yaml in the folder is treated as a migration.

**Comment by tkivisik** [comment]
I believe you are talking about yaml files which are intended to be used as part of gmig. There are also files which one would not like to be treated as part of gmig. Currently, there is no such option.

I see that considering all yaml files as part of gmig in these cases for example:

- When making a script to produce gmig migrations, and these scripts might prefer using yaml themselves.
- When part of the code of what will be applied with a migration sits in a gmig folder, and some of that code prefers yaml.
==> These lead to unexpected behaviour. I'm leaning towards considering it undesireable, and would prefer restricting at least a bit (maybe not as strictly as I did currently. Maybe it should allow all yaml files either starting with a timestamp or an index, which can be a sequence of any length of digits followed by an underscore, instead of a rigid 3). Currently you are leaning towards no restriction at all?

**Comment by emicklei** [comment]
so, looking at all our infra projects (for each service, we have a infra git project describing the changes of infrastructure), we have a folder/file structure that looks like this:

```
my-service-infra/
my-service-infra/migrations/
my-service-infra/migrations/20180218t213702_add_loadrunner_service_account.yaml
my-service-infra/migrations/20180218t213927_allow_loadrunner_to_access_gcs.yaml
my-service-infra/migrations/staging
my-service-infra/migrations/staging/gmig.json
my-service-infra/migrations/production
my-service-infra/migrations/production/gmig.json
```

So to run the migrations, we cd to `migrations` and execute `gmig up staging`.

The point here is by simply putting the migrations files together in a folder (here migrations), is telling the developer/maintainer how these should be used.  It is just a convention. 
If someone puts another yaml file inside the migrations folder for another program to read then yes this breaks the gmig tool. It is not hard to find similar examples.

**Comment by tkivisik** [comment]
Say there is a custom Cloud Function which is set up by gmig.

Then the current solution would be to keep that custom cloud function in`my-service-infra/custom-cloud-function` and keep the `my-service-infra/migrations/` strictly for gmig files. That means, considering `my-service-infra/migrations/` folder for everything related to infrastructure setup is discouraged.

Proposed restriction would make it possible to also keep everything infrastructure setup related under `my-service-infra/migrations/` folder.

**Comment by emicklei** [comment]
yes, i understand. We keep deployment en infrastructure separated.  The deployment (yaml) files are in the my-service project. 
The reason why we separated infra into a different git project is because both can different lifecycles and use git tags for different purposes. 

We have setup a Cloud Build trigger that listens to tags of the infra project and executes the infra updates using gmig.
We have another Cloud Build trigger that listens to tags of my-service and perform builds,tests and perf tests. Only on success of that build, we tag the infra project such that a new service gets deployed.

I recall a moment when designing gmig that perhaps the migrations files should have their own extensions, e.g.  010_allow_loadrunner_to_access_gcs.gmig.  But then most editors do not recognise it and the therefore will not help linting it.

I understand you case and see that is causes problems but I think keeping files organised in the right folder really helps maintaining bigger projects.
